smash> smash> smash: got ctrl-Z
smash: process \d+ was stopped
smash> \[1\] timeout 110 sleep 20 & : \d+ \d+ secs
\[2\] sleep 150 : \d+ \d+ secs \(stopped\)
smash> smash: got ctrl-C
smash: process \d+ was killed
smash> \[1\] timeout 110 sleep 20 & : \d+ \d+ secs
\[2\] sleep 150 : \d+ \d+ secs \(stopped\)
smash> smash> klfjfdsfkjdsfjkkjfkjlewfkjjkl erkjlf
f;oksdfljdgjkdfasd
flkdslfvker
f lofkopewrf
 f ofdopd 
 
 fvofpokrkp
 
 kofdkopkfoew
 
 olfgkrokl;kl;k;lkl;fd
 kkkkkk490r943ioijojifgjfiofgiojrfiowiofo
 likfdhgjihofioehr
 pofdgpoerpojfjp43
 ;lkkrkjfjovojijiorlkjknjnfklgerkj
 098vuu3jfjifiioriohufo
 tamirtest lkjfekjlfjk
 skljdfjkldsfjklsd
 tamirtest fkljsdkfjksd
 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3 kjerjferfjk
 jfhk3jhfjh3diojsffffffffffffffffffffffffffffffffffffffffffr83489ru834
 pofidofii349r34utfujre
 flodsoksopifiowesmash> smash>  tamirtest lkjfekjlfjk
 tamirtest fkljsdkfjksd
smash> smash> tamirtest 1234                                                                               
tamirtest 1234
tamirtest 1234
tamirtest 5678                                                                               
tamirtest 5678                                                                               
tamirtest 5678                                                                               
tamirtest 1234
tamirtest 5678                                                                               
tamirtest 5678                                                                               
tamirtest 1234
smash> tamirtest 1234                                                                               
tamirtest 1234
tamirtest 1234
tamirtest 5678                                                                               
tamirtest 5678                                                                               
tamirtest 5678                                                                               
tamirtest 1234
tamirtest 5678                                                                               
tamirtest 5678                                                                               
tamirtest 1234smash> smash> smash> smash> \[1\] timeout 110 sleep 20 & : \d+ \d+ secs
\[2\] sleep 150 : \d+ \d+ secs \(stopped\)
\[3\] timeout 15 sleep 5& : \d+ \d+ secs
\[4\] timeout 10 sleep 16& : \d+ \d+ secs
\[5\] timeout 30 sleep 7 & : \d+ \d+ secs
smash> smash: got an alarm
smash: got an alarm
smash: timeout 10 sleep 16& timed out!
smash: got an alarm
smash: got ctrl-C
smash: got ctrl-Z
smash pid is \d+
smash> smash pid is \d+
smash> smash: got ctrl-Z
\[2\] sleep 150 : \d+ \d+ secs \(stopped\)
smash> smash: got an alarm
sleep 150 : \d+
smash: got ctrl-Z
smash: process \d+ was stopped
smash> \[2\] sleep 150 : \d+ \d+ secs \(stopped\)
smash> smash> smash> sleep 15& : \d+
smash: got ctrl-Z
smash: process \d+ was stopped
smash> \[2\] sleep 150 : \d+ \d+ secs \(stopped\)
\[3\] sleep 15& : \d+ \d+ secs \(stopped\)
\[4\] sleep 100& : \d+ \d+ secs
smash> sleep 15& : \d+
smash> \[2\] sleep 150 : \d+ \d+ secs \(stopped\)
\[3\] sleep 15& : \d+ \d+ secs
\[4\] sleep 100& : \d+ \d+ secs
smash> smash> signal number 9 was sent to pid \d+
smash> \[2\] sleep 150 : \d+ \d+ secs \(stopped\)
\[5\] timeout 20 sleep 150& : \d+ \d+ secs
smash> smash error: kill: job-id 3 does not exist
smash> smash> smash error: kill: job-id 3 does not exist
smash> smash: got an alarm
smash: timeout 20 sleep 150& timed out!
\[2\] sleep 150 : \d+ \d+ secs \(stopped\)
\[6\] sleep 200& : \d+ \d+ secs
smash> smash> smash> smash> \[2\] sleep 150 : \d+ \d+ secs \(stopped\)
\[6\] sleep 200& : \d+ \d+ secs
\[7\] sleep 100& : \d+ \d+ secs
\[8\] sleep 200& : \d+ \d+ secs
\[9\] sleep 500 & : \d+ \d+ secs
smash> signal number 19 was sent to pid \d+
smash> smash> signal number 18 was sent to pid \d+
smash> \[2\] sleep 150 : \d+ \d+ secs \(stopped\)
\[6\] sleep 200& : \d+ \d+ secs
\[7\] sleep 100& : \d+ \d+ secs
\[8\] sleep 200& : \d+ \d+ secs
\[9\] sleep 500 & : \d+ \d+ secs
\[10\] sleep 200& : \d+ \d+ secs
smash> sleep 200& : \d+
smash: got ctrl-Z
smash: process \d+ was stopped
smash> sleep 100& : \d+
smash: got an alarm
smash: got ctrl-Z
smash: process \d+ was stopped
smash> sleep 200& : \d+
smash: got ctrl-C
smash: process \d+ was killed
smash> \[2\] sleep 150 : \d+ \d+ secs \(stopped\)
\[6\] sleep 200& : \d+ \d+ secs
\[7\] sleep 100& : \d+ \d+ secs \(stopped\)
\[9\] sleep 500 & : \d+ \d+ secs
\[10\] sleep 200& : \d+ \d+ secs \(stopped\)
smash> smash> /tmp/smash_test
smash> smash error: cd: OLDPWD not set
smash> smash error: cd: OLDPWD not set
smash> /tmp/smash_test
smash> smash> smash: got an alarm
smash: timeout 10 sleep 150& timed out!
did I pass the test?
smash> smash> did I pass the test?
I hope so
smash> Bye Bye
smash> smash: sending SIGKILL signal to 5 jobs:
\d+: sleep 150
\d+: sleep 200&
\d+: sleep 100&
\d+: sleep 500 &
\d+: sleep 200&
